name: BEBIM CI

on:
  push:
    branches:
      - feature-16
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unittests
        run: |
          python -m unittest -v tests.test_beam
          python -m unittest -v tests.test_species
          python -m unittest -v tests.test_cross_section
          python -m unittest -v tests.test_tabata